0:00:05.215682 0:00:00.004634 0:00:05.211048
0:00:03.662377 0:00:00.044078 0:00:03.618299
0:00:11.134401 0:00:00.107442 0:00:11.026959
Traceback (most recent call last):
  File "invoke.py", line 106, in <module>
    invoker(size, org, space, fname, loop, mat_n)
  File "invoke.py", line 87, in invoker
    rall[rdict['activationId']] = rdict
KeyError: 'activationId'
0:00:18.949134 0:00:00.219473 0:00:18.729661
